name: Simple CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Compile
      run: |
        mkdir -p bin
        find src -name "*.java" -print0 | xargs -0 javac -d bin -cp src
        
    - name: Package JAR
      run: |
        cd bin
        jar -cf ../vaultpin-banking-system.jar com/
        cd ..
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: vaultpin-banking-system
        path: vaultpin-banking-system.jar